// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.2
// source: care_companion.proto

package care_companion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location_Country int32

const (
	Location_UNKNOWN_COUNTRY Location_Country = 0
	Location_IRAN            Location_Country = 1
)

// Enum value maps for Location_Country.
var (
	Location_Country_name = map[int32]string{
		0: "UNKNOWN_COUNTRY",
		1: "IRAN",
	}
	Location_Country_value = map[string]int32{
		"UNKNOWN_COUNTRY": 0,
		"IRAN":            1,
	}
)

func (x Location_Country) Enum() *Location_Country {
	p := new(Location_Country)
	*p = x
	return p
}

func (x Location_Country) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Location_Country) Descriptor() protoreflect.EnumDescriptor {
	return file_care_companion_proto_enumTypes[0].Descriptor()
}

func (Location_Country) Type() protoreflect.EnumType {
	return &file_care_companion_proto_enumTypes[0]
}

func (x Location_Country) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Location_Country.Descriptor instead.
func (Location_Country) EnumDescriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{10, 0}
}

type Location_City int32

const (
	Location_UNKNOWN_CITY Location_City = 0
	Location_TEHRAN       Location_City = 1
)

// Enum value maps for Location_City.
var (
	Location_City_name = map[int32]string{
		0: "UNKNOWN_CITY",
		1: "TEHRAN",
	}
	Location_City_value = map[string]int32{
		"UNKNOWN_CITY": 0,
		"TEHRAN":       1,
	}
)

func (x Location_City) Enum() *Location_City {
	p := new(Location_City)
	*p = x
	return p
}

func (x Location_City) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Location_City) Descriptor() protoreflect.EnumDescriptor {
	return file_care_companion_proto_enumTypes[1].Descriptor()
}

func (Location_City) Type() protoreflect.EnumType {
	return &file_care_companion_proto_enumTypes[1]
}

func (x Location_City) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Location_City.Descriptor instead.
func (Location_City) EnumDescriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{10, 1}
}

type Location_Neighborhood int32

const (
	Location_UNKNOWN_NEIGHBORHOOD Location_Neighborhood = 0
	Location_SAADAT_AABAAD        Location_Neighborhood = 1
)

// Enum value maps for Location_Neighborhood.
var (
	Location_Neighborhood_name = map[int32]string{
		0: "UNKNOWN_NEIGHBORHOOD",
		1: "SAADAT_AABAAD",
	}
	Location_Neighborhood_value = map[string]int32{
		"UNKNOWN_NEIGHBORHOOD": 0,
		"SAADAT_AABAAD":        1,
	}
)

func (x Location_Neighborhood) Enum() *Location_Neighborhood {
	p := new(Location_Neighborhood)
	*p = x
	return p
}

func (x Location_Neighborhood) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Location_Neighborhood) Descriptor() protoreflect.EnumDescriptor {
	return file_care_companion_proto_enumTypes[2].Descriptor()
}

func (Location_Neighborhood) Type() protoreflect.EnumType {
	return &file_care_companion_proto_enumTypes[2]
}

func (x Location_Neighborhood) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Location_Neighborhood.Descriptor instead.
func (Location_Neighborhood) EnumDescriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{10, 2}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_care_companion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_care_companion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_care_companion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_care_companion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCareSeekerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCareSeekerRequest) Reset() {
	*x = GetCareSeekerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_care_companion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCareSeekerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCareSeekerRequest) ProtoMessage() {}

func (x *GetCareSeekerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_care_companion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCareSeekerRequest.ProtoReflect.Descriptor instead.
func (*GetCareSeekerRequest) Descriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{2}
}

func (x *GetCareSeekerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCareSeekerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CareSeeker *CareSeeker `protobuf:"bytes,1,opt,name=care_seeker,json=careSeeker,proto3" json:"care_seeker,omitempty"`
}

func (x *GetCareSeekerResponse) Reset() {
	*x = GetCareSeekerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_care_companion_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCareSeekerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCareSeekerResponse) ProtoMessage() {}

func (x *GetCareSeekerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_care_companion_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCareSeekerResponse.ProtoReflect.Descriptor instead.
func (*GetCareSeekerResponse) Descriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{3}
}

func (x *GetCareSeekerResponse) GetCareSeeker() *CareSeeker {
	if x != nil {
		return x.CareSeeker
	}
	return nil
}

type CreateCareSeekerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateCareSeekerRequest) Reset() {
	*x = CreateCareSeekerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_care_companion_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCareSeekerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCareSeekerRequest) ProtoMessage() {}

func (x *CreateCareSeekerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_care_companion_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCareSeekerRequest.ProtoReflect.Descriptor instead.
func (*CreateCareSeekerRequest) Descriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCareSeekerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCareSeekerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CareSeeker *CareSeeker `protobuf:"bytes,1,opt,name=care_seeker,json=careSeeker,proto3" json:"care_seeker,omitempty"`
}

func (x *CreateCareSeekerResponse) Reset() {
	*x = CreateCareSeekerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_care_companion_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCareSeekerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCareSeekerResponse) ProtoMessage() {}

func (x *CreateCareSeekerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_care_companion_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCareSeekerResponse.ProtoReflect.Descriptor instead.
func (*CreateCareSeekerResponse) Descriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCareSeekerResponse) GetCareSeeker() *CareSeeker {
	if x != nil {
		return x.CareSeeker
	}
	return nil
}

type CreateCareNeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CareSeekerId string `protobuf:"bytes,1,opt,name=care_seeker_id,json=careSeekerId,proto3" json:"care_seeker_id,omitempty"`
}

func (x *CreateCareNeedRequest) Reset() {
	*x = CreateCareNeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_care_companion_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCareNeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCareNeedRequest) ProtoMessage() {}

func (x *CreateCareNeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_care_companion_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCareNeedRequest.ProtoReflect.Descriptor instead.
func (*CreateCareNeedRequest) Descriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCareNeedRequest) GetCareSeekerId() string {
	if x != nil {
		return x.CareSeekerId
	}
	return ""
}

type CreateCareNeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CareNeed *CareNeed `protobuf:"bytes,1,opt,name=care_need,json=careNeed,proto3" json:"care_need,omitempty"`
}

func (x *CreateCareNeedResponse) Reset() {
	*x = CreateCareNeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_care_companion_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCareNeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCareNeedResponse) ProtoMessage() {}

func (x *CreateCareNeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_care_companion_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCareNeedResponse.ProtoReflect.Descriptor instead.
func (*CreateCareNeedResponse) Descriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCareNeedResponse) GetCareNeed() *CareNeed {
	if x != nil {
		return x.CareNeed
	}
	return nil
}

type GetCareNeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Id:
	//
	//	*GetCareNeedRequest_CareSeekerId
	//	*GetCareNeedRequest_CareNeedId
	Id isGetCareNeedRequest_Id `protobuf_oneof:"id"`
}

func (x *GetCareNeedRequest) Reset() {
	*x = GetCareNeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_care_companion_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCareNeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCareNeedRequest) ProtoMessage() {}

func (x *GetCareNeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_care_companion_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCareNeedRequest.ProtoReflect.Descriptor instead.
func (*GetCareNeedRequest) Descriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{8}
}

func (m *GetCareNeedRequest) GetId() isGetCareNeedRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (x *GetCareNeedRequest) GetCareSeekerId() string {
	if x, ok := x.GetId().(*GetCareNeedRequest_CareSeekerId); ok {
		return x.CareSeekerId
	}
	return ""
}

func (x *GetCareNeedRequest) GetCareNeedId() string {
	if x, ok := x.GetId().(*GetCareNeedRequest_CareNeedId); ok {
		return x.CareNeedId
	}
	return ""
}

type isGetCareNeedRequest_Id interface {
	isGetCareNeedRequest_Id()
}

type GetCareNeedRequest_CareSeekerId struct {
	CareSeekerId string `protobuf:"bytes,1,opt,name=care_seeker_id,json=careSeekerId,proto3,oneof"`
}

type GetCareNeedRequest_CareNeedId struct {
	CareNeedId string `protobuf:"bytes,2,opt,name=care_need_id,json=careNeedId,proto3,oneof"`
}

func (*GetCareNeedRequest_CareSeekerId) isGetCareNeedRequest_Id() {}

func (*GetCareNeedRequest_CareNeedId) isGetCareNeedRequest_Id() {}

type GetCareNeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CareNeed *CareNeed `protobuf:"bytes,1,opt,name=care_need,json=careNeed,proto3" json:"care_need,omitempty"`
}

func (x *GetCareNeedResponse) Reset() {
	*x = GetCareNeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_care_companion_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCareNeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCareNeedResponse) ProtoMessage() {}

func (x *GetCareNeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_care_companion_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCareNeedResponse.ProtoReflect.Descriptor instead.
func (*GetCareNeedResponse) Descriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{9}
}

func (x *GetCareNeedResponse) GetCareNeed() *CareNeed {
	if x != nil {
		return x.CareNeed
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country      Location_Country      `protobuf:"varint,1,opt,name=country,proto3,enum=care_companion.Location_Country" json:"country,omitempty"`
	City         Location_City         `protobuf:"varint,2,opt,name=city,proto3,enum=care_companion.Location_City" json:"city,omitempty"`
	Neighborhood Location_Neighborhood `protobuf:"varint,3,opt,name=neighborhood,proto3,enum=care_companion.Location_Neighborhood" json:"neighborhood,omitempty"`
	Latitude     float32               `protobuf:"fixed32,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude    float32               `protobuf:"fixed32,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_care_companion_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_care_companion_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{10}
}

func (x *Location) GetCountry() Location_Country {
	if x != nil {
		return x.Country
	}
	return Location_UNKNOWN_COUNTRY
}

func (x *Location) GetCity() Location_City {
	if x != nil {
		return x.City
	}
	return Location_UNKNOWN_CITY
}

func (x *Location) GetNeighborhood() Location_Neighborhood {
	if x != nil {
		return x.Neighborhood
	}
	return Location_UNKNOWN_NEIGHBORHOOD
}

func (x *Location) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type CareSeeker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CareSeeker) Reset() {
	*x = CareSeeker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_care_companion_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CareSeeker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareSeeker) ProtoMessage() {}

func (x *CareSeeker) ProtoReflect() protoreflect.Message {
	mi := &file_care_companion_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareSeeker.ProtoReflect.Descriptor instead.
func (*CareSeeker) Descriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{11}
}

func (x *CareSeeker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CareSeeker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CareNeed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Location     *Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Compensation float64   `protobuf:"fixed64,3,opt,name=compensation,proto3" json:"compensation,omitempty"`
}

func (x *CareNeed) Reset() {
	*x = CareNeed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_care_companion_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CareNeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareNeed) ProtoMessage() {}

func (x *CareNeed) ProtoReflect() protoreflect.Message {
	mi := &file_care_companion_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareNeed.ProtoReflect.Descriptor instead.
func (*CareNeed) Descriptor() ([]byte, []int) {
	return file_care_companion_proto_rawDescGZIP(), []int{12}
}

func (x *CareNeed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CareNeed) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *CareNeed) GetCompensation() float64 {
	if x != nil {
		return x.Compensation
	}
	return 0
}

var File_care_companion_proto protoreflect.FileDescriptor

var file_care_companion_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x28, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x54, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65, 0x6b,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x61,
	0x72, 0x65, 0x5f, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e,
	0x2e, 0x43, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x52, 0x0a, 0x63, 0x61, 0x72,
	0x65, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x22, 0x2d, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x57, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x65, 0x6b, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65,
	0x6b, 0x65, 0x72, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x22,
	0x3d, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x65, 0x4e, 0x65, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x61, 0x72, 0x65,
	0x5f, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4f,
	0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x65, 0x4e, 0x65, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x65,
	0x5f, 0x6e, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x61,
	0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x72,
	0x65, 0x4e, 0x65, 0x65, 0x64, 0x52, 0x08, 0x63, 0x61, 0x72, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x22,
	0x66, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x73, 0x65,
	0x65, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x0c, 0x63, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x6e, 0x65, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x49,
	0x64, 0x42, 0x04, 0x0a, 0x02, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x72, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35,
	0x0a, 0x09, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x6e, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69,
	0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x72, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x52, 0x08, 0x63, 0x61, 0x72,
	0x65, 0x4e, 0x65, 0x65, 0x64, 0x22, 0x8b, 0x03, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x31,
	0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x63,
	0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x52, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x49, 0x0a, 0x0c, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x52, 0x0c,
	0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x28, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x43, 0x4f, 0x55,
	0x4e, 0x54, 0x52, 0x59, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x52, 0x41, 0x4e, 0x10, 0x01,
	0x22, 0x24, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x5f, 0x43, 0x49, 0x54, 0x59, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x45,
	0x48, 0x52, 0x41, 0x4e, 0x10, 0x01, 0x22, 0x3b, 0x0a, 0x0c, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62,
	0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x12, 0x18, 0x0a, 0x14, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x5f, 0x4e, 0x45, 0x49, 0x47, 0x48, 0x42, 0x4f, 0x52, 0x48, 0x4f, 0x4f, 0x44, 0x10, 0x00,
	0x12, 0x11, 0x0a, 0x0d, 0x53, 0x41, 0x41, 0x44, 0x41, 0x54, 0x5f, 0x41, 0x41, 0x42, 0x41, 0x41,
	0x44, 0x10, 0x01, 0x22, 0x30, 0x0a, 0x0a, 0x43, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65, 0x6b, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x74, 0x0a, 0x08, 0x43, 0x61, 0x72, 0x65, 0x4e, 0x65, 0x65,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x34, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x65,
	0x6e, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x63,
	0x6f, 0x6d, 0x70, 0x65, 0x6e, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xca, 0x03, 0x0a, 0x0d,
	0x43, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x5c, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x12, 0x24,
	0x2e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65,
	0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x10, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x12,
	0x27, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65, 0x6b, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x5f,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x72, 0x65, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x56, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x65, 0x4e, 0x65, 0x65,
	0x64, 0x12, 0x22, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69,
	0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x65, 0x4e, 0x65,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x12, 0x25, 0x2e, 0x63,
	0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x65, 0x4e, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x65, 0x4e,
	0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x04, 0x50,
	0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1c, 0x2e, 0x63, 0x61, 0x72,
	0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6f, 0x6d, 0x61, 0x79, 0x6f, 0x6f, 0x6e, 0x61,
	0x6c, 0x69, 0x6d, 0x6f, 0x68, 0x61, 0x6d, 0x6d, 0x61, 0x64, 0x69, 0x2f, 0x63, 0x61, 0x72, 0x65,
	0x2d, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_care_companion_proto_rawDescOnce sync.Once
	file_care_companion_proto_rawDescData = file_care_companion_proto_rawDesc
)

func file_care_companion_proto_rawDescGZIP() []byte {
	file_care_companion_proto_rawDescOnce.Do(func() {
		file_care_companion_proto_rawDescData = protoimpl.X.CompressGZIP(file_care_companion_proto_rawDescData)
	})
	return file_care_companion_proto_rawDescData
}

var file_care_companion_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_care_companion_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_care_companion_proto_goTypes = []interface{}{
	(Location_Country)(0),            // 0: care_companion.Location.Country
	(Location_City)(0),               // 1: care_companion.Location.City
	(Location_Neighborhood)(0),       // 2: care_companion.Location.Neighborhood
	(*Empty)(nil),                    // 3: care_companion.Empty
	(*PingResponse)(nil),             // 4: care_companion.PingResponse
	(*GetCareSeekerRequest)(nil),     // 5: care_companion.GetCareSeekerRequest
	(*GetCareSeekerResponse)(nil),    // 6: care_companion.GetCareSeekerResponse
	(*CreateCareSeekerRequest)(nil),  // 7: care_companion.CreateCareSeekerRequest
	(*CreateCareSeekerResponse)(nil), // 8: care_companion.CreateCareSeekerResponse
	(*CreateCareNeedRequest)(nil),    // 9: care_companion.CreateCareNeedRequest
	(*CreateCareNeedResponse)(nil),   // 10: care_companion.CreateCareNeedResponse
	(*GetCareNeedRequest)(nil),       // 11: care_companion.GetCareNeedRequest
	(*GetCareNeedResponse)(nil),      // 12: care_companion.GetCareNeedResponse
	(*Location)(nil),                 // 13: care_companion.Location
	(*CareSeeker)(nil),               // 14: care_companion.CareSeeker
	(*CareNeed)(nil),                 // 15: care_companion.CareNeed
}
var file_care_companion_proto_depIdxs = []int32{
	14, // 0: care_companion.GetCareSeekerResponse.care_seeker:type_name -> care_companion.CareSeeker
	14, // 1: care_companion.CreateCareSeekerResponse.care_seeker:type_name -> care_companion.CareSeeker
	15, // 2: care_companion.CreateCareNeedResponse.care_need:type_name -> care_companion.CareNeed
	15, // 3: care_companion.GetCareNeedResponse.care_need:type_name -> care_companion.CareNeed
	0,  // 4: care_companion.Location.country:type_name -> care_companion.Location.Country
	1,  // 5: care_companion.Location.city:type_name -> care_companion.Location.City
	2,  // 6: care_companion.Location.neighborhood:type_name -> care_companion.Location.Neighborhood
	13, // 7: care_companion.CareNeed.location:type_name -> care_companion.Location
	5,  // 8: care_companion.CareCompanion.GetCareSeeker:input_type -> care_companion.GetCareSeekerRequest
	7,  // 9: care_companion.CareCompanion.CreateCareSeeker:input_type -> care_companion.CreateCareSeekerRequest
	11, // 10: care_companion.CareCompanion.GetCareNeed:input_type -> care_companion.GetCareNeedRequest
	9,  // 11: care_companion.CareCompanion.CreateCareNeed:input_type -> care_companion.CreateCareNeedRequest
	3,  // 12: care_companion.CareCompanion.Ping:input_type -> care_companion.Empty
	6,  // 13: care_companion.CareCompanion.GetCareSeeker:output_type -> care_companion.GetCareSeekerResponse
	8,  // 14: care_companion.CareCompanion.CreateCareSeeker:output_type -> care_companion.CreateCareSeekerResponse
	12, // 15: care_companion.CareCompanion.GetCareNeed:output_type -> care_companion.GetCareNeedResponse
	10, // 16: care_companion.CareCompanion.CreateCareNeed:output_type -> care_companion.CreateCareNeedResponse
	4,  // 17: care_companion.CareCompanion.Ping:output_type -> care_companion.PingResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_care_companion_proto_init() }
func file_care_companion_proto_init() {
	if File_care_companion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_care_companion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_care_companion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_care_companion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCareSeekerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_care_companion_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCareSeekerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_care_companion_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCareSeekerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_care_companion_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCareSeekerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_care_companion_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCareNeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_care_companion_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCareNeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_care_companion_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCareNeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_care_companion_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCareNeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_care_companion_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_care_companion_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CareSeeker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_care_companion_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CareNeed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_care_companion_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*GetCareNeedRequest_CareSeekerId)(nil),
		(*GetCareNeedRequest_CareNeedId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_care_companion_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_care_companion_proto_goTypes,
		DependencyIndexes: file_care_companion_proto_depIdxs,
		EnumInfos:         file_care_companion_proto_enumTypes,
		MessageInfos:      file_care_companion_proto_msgTypes,
	}.Build()
	File_care_companion_proto = out.File
	file_care_companion_proto_rawDesc = nil
	file_care_companion_proto_goTypes = nil
	file_care_companion_proto_depIdxs = nil
}
