// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CareSeek struct {
	ID           int64
	LocationID   int64
	Compensation pgtype.Numeric
	CareSeekerID int64
}

type CareSeeker struct {
	ID   int64
	Name string
}

type City struct {
	ID        int64
	Name      string
	CountryID int64
}

type Country struct {
	ID   int64
	Name string
}

type Location struct {
	ID             int64
	CountryID      int64
	CityID         int64
	NeighborhoodID pgtype.Int8
	Latitude       pgtype.Numeric
	Longitude      pgtype.Numeric
}

type Neighborhood struct {
	ID     int64
	Name   string
	CityID int64
}
