// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package queries

import (
	"context"
)

type Querier interface {
	CreateCareSeeker(ctx context.Context, db DBTX, name string) error
	DeleteCareSeekerByID(ctx context.Context, db DBTX, id int64) error
	DeleteCareSeekerByName(ctx context.Context, db DBTX, name string) error
	GetCareSeekerByID(ctx context.Context, db DBTX, id int64) (CareSeeker, error)
	GetCareSeekerByName(ctx context.Context, db DBTX, name string) (CareSeeker, error)
	UpdateCareSeeker(ctx context.Context, db DBTX, arg UpdateCareSeekerParams) error
}

var _ Querier = (*Queries)(nil)
